const data = [
  {
    appCode: 'saba',
    childrenMenus: [
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '店铺管理',
        leaf: false,
        parentId: 6000003226,
        resIcon: 'deployment-unit',
        resName: '店铺管理',
        resType: 'MENU',
        resValue: '/home/shop',
        securityId: 'Ip_3J-fn8KKWa6A2O0IhyA',
        sortId: 10,
        childrenMenus: [
          {
            appCode: 'saba',
            deepLength: 0,
            displayName: '店铺管理2',
            leaf: false,
            parentId: 6000003226,
            resIcon: 'deployment-unit',
            resName: '店铺管理2',
            resType: 'MENU',
            resValue: '/home/shop/test2',
            securityId: 'Ip_3J-fn8KKWa6A2O0IhyA',
            sortId: 10,
          },
        ],
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '电商平台管理',
        leaf: false,
        parentId: 6000003226,
        resIcon: 'deployment-unit',
        resName: '电商平台管理',
        resType: 'MENU',
        resValue: '/home/platform',
        securityId: 'ladCY4Igqb44ezjcTWsUXA',
        sortId: 20,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '网站管理',
        leaf: false,
        parentId: 6000003226,
        resIcon: 'deployment-unit',
        resName: '网站管理',
        resType: 'MENU',
        resValue: '/home/website',
        securityId: 'wAjLbDr5wQgehQH01918aA',
        sortId: 30,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '移动应用平台',
        leaf: false,
        parentId: 6000003226,
        resIcon: 'deployment-unit',
        resName: '移动应用平台',
        resType: 'MENU',
        resValue: '/home/mobile-app',
        securityId: 'lSyrIsmeLAlEV9ERA-YiIA',
        sortId: 40,
      },
    ],
    deepLength: 0,
    displayName: '主体库',
    leaf: false,
    resIcon: 'icon-zhutiku',
    resName: '主体库',
    resType: 'MENU',
    resValue: '/home/subject',
    securityId: '5SDVvAiAnapI93DEnXkckA',
    sortId: 10,
  },
  {
    appCode: 'saba',
    deepLength: 0,
    displayName: '客体库',
    leaf: false,
    resIcon: 'icon-ketiku',
    resName: '客体库',
    resType: 'MENU',
    resValue: '/home/client',
    securityId: '-Y06hsD-WjFlY0eTgSFZ1g',
    sortId: 20,
  },
  {
    appCode: 'saba',
    deepLength: 0,
    displayName: '取证中心',
    leaf: false,
    resIcon: 'icon-quzhengzhongxin',
    resName: '取证中心',
    resType: 'MENU',
    resValue: '/home/forensic-center',
    securityId: 'qPvnWcKgoTM8P5-Ysto0jA',
    sortId: 30,
  },
  {
    appCode: 'saba',
    childrenMenus: [
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '企业注册信息',
        leaf: false,
        parentId: 6000003233,
        resIcon: 'deployment-unit',
        resName: '企业注册信息',
        resType: 'MENU',
        resValue: '/home/registration/company-registration-message',
        securityId: 'PgSf8R7bP8xlqkFzy_yrFA',
        sortId: 10,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '个体注册信息',
        leaf: false,
        parentId: 6000003233,
        resIcon: 'deployment-unit',
        resName: '个体注册信息',
        resType: 'MENU',
        resValue: '/home/registration/personal-registration-message',
        securityId: 'p1HnpiB1iLrK4_B-FHSWcw',
        sortId: 20,
      },
    ],
    deepLength: 0,
    displayName: '注册信息管理',
    leaf: false,
    resIcon: 'icon-zhucexinxiguanli',
    resName: '注册信息管理',
    resType: 'MENU',
    resValue: '/home/registration',
    securityId: '96kdaA8qEtqROlWoonOyJw',
    sortId: 40,
  },
  {
    appCode: 'saba',
    childrenMenus: [
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '主体分布统计',
        leaf: false,
        parentId: 6000003236,
        resIcon: 'deployment-unit',
        resName: '主体分布统计',
        resType: 'MENU',
        resValue: '/home/monitor-report/entity-statistic',
        securityId: 'XEcsxSXxy7T2ay3IxTu2EQ',
        sortId: 10,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '数据采集监控',
        leaf: false,
        parentId: 6000003236,
        resIcon: 'deployment-unit',
        resName: '数据采集监控',
        resType: 'MENU',
        resValue: '/home/monitor-report/collection-monitor',
        securityId: 'xvaRZvl4Zw62U1hvd-21ng',
        sortId: 20,
      },
    ],
    deepLength: 0,
    displayName: '监测报告',
    leaf: false,
    resIcon: 'icon-jiancebaogao',
    resName: '监测报告',
    resType: 'MENU',
    resValue: '/home/monitor-report',
    securityId: 'o6H2EnJXuR74iAGOrvr85A',
    sortId: 50,
  },
  {
    appCode: 'saba',
    childrenMenus: [
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '电商平台管理',
        leaf: false,
        parentId: 6000003239,
        resIcon: 'deployment-unit',
        resName: '电商平台管理',
        resType: 'MENU',
        resValue: '/home/ecommerce',
        securityId: 'xIx8bBo2gFt1WtWngJXEtQ',
        sortId: 10,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '电商平台类目管理',
        leaf: false,
        parentId: 6000003239,
        resIcon: 'deployment-unit',
        resName: '电商平台类目管理',
        resType: 'MENU',
        resValue: '/home/category',
        securityId: 'j31SLVJ_0GVigqF51wJXxQ',
        sortId: 20,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '采集任务管理',
        leaf: false,
        parentId: 6000003239,
        resIcon: 'deployment-unit',
        resName: '采集任务管理',
        resType: 'MENU',
        resValue: '/home/collection-manager',
        securityId: 'CJ2nGHYKdFe8PW9dtBtYpQ',
        sortId: 30,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '采集结果',
        leaf: false,
        parentId: 6000003239,
        resIcon: 'deployment-unit',
        resName: '采集结果',
        resType: 'MENU',
        resValue: '/home/collection-result',
        securityId: 'YK88ajeYvP9b6t30Hhe9gA',
        sortId: 40,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '平台规则采集协议',
        leaf: false,
        parentId: 6000003239,
        resIcon: 'deployment-unit',
        resName: '平台规则采集协议',
        resType: 'MENU',
        resValue: '/home/agreement-result',
        securityId: 'MDP5kyd6B0V48Wg9lteSMQ',
        sortId: 50,
      },
    ],
    deepLength: 0,
    displayName: '采集任务调度',
    leaf: false,
    resIcon: 'icon-caijirenwutiaodu',
    resName: '采集任务调度',
    resType: 'MENU',
    resValue: '/home/collection',
    securityId: 'Od_JQtN7lJrNjJau1vfZRA',
    sortId: 60,
  },
  {
    appCode: 'saba',
    childrenMenus: [
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '用户管理',
        leaf: false,
        parentId: 6000003245,
        resIcon: 'deployment-unit',
        resName: '用户管理',
        resType: 'MENU',
        resValue: '/home/account/user-management',
        securityId: 'xuvjO0SfqtIpdg95rTkkWA',
        sortId: 10,
      },
    ],
    deepLength: 0,
    displayName: '账号管理',
    leaf: false,
    resIcon: 'icon-zhanghaoguanli',
    resName: '账号管理',
    resType: 'MENU',
    resValue: '/home/account',
    securityId: 'MvqDWUWqIAU9YkHVlXoneA',
    sortId: 70,
  },
  {
    appCode: 'saba',
    childrenMenus: [
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '操作日志',
        leaf: false,
        parentId: 6000003247,
        resIcon: 'deployment-unit',
        resName: '操作日志',
        resType: 'MENU',
        resValue: '/home/system-setting/operation-log',
        securityId: '6yeVHyxpDvgawvJlHSSKHA',
        sortId: 10,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '采集任务调度设置',
        leaf: false,
        parentId: 6000003247,
        resIcon: 'deployment-unit',
        resName: '采集任务调度设置',
        resType: 'MENU',
        resValue: '/home/system-setting/collection-setting',
        securityId: 'kqXMWCHByE4pogrPNCa_sQ',
        sortId: 20,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '数据管理-主体库',
        leaf: false,
        parentId: 6000003247,
        resIcon: 'deployment-unit',
        resName: '数据管理-主体库',
        resType: 'MENU',
        resValue: '/home/system-setting/subject-library',
        securityId: 'UDmZow25J9zW4oFcpYIs8g',
        sortId: 30,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '数据管理-风险配置',
        leaf: false,
        parentId: 6000003247,
        resIcon: 'deployment-unit',
        resName: '数据管理-风险配置',
        resType: 'MENU',
        resValue: 'null/riskTagImport.htm',
        securityId: 'P-C7e4Q2EQulRr6EtKFoiQ',
        sortId: 35,
      },
      {
        appCode: 'saba',
        deepLength: 0,
        displayName: '标签管理',
        leaf: false,
        parentId: 6000003247,
        resIcon: 'deployment-unit',
        resName: '标签管理',
        resType: 'MENU',
        resValue: '/home/system-setting/tag-manager',
        securityId: 'fj10r6S33susiqIpGmDSqA',
        sortId: 40,
      },
    ],
    deepLength: 0,
    displayName: '系统设置',
    leaf: false,
    resIcon: 'icon-xitongshezhi',
    resName: '系统设置',
    resType: 'MENU',
    resValue: '/home/system-setting',
    securityId: 'Bcs6RAydeHAiEqE9iCh59g',
    sortId: 80,
  },
];

export default data;
